Jupyter Support + Bug Fix
qsharp-community/chp-sim pull request #9
Opened 2020-07-25 03:53 UTC by crazy4pi314

So this fixes #7 and in the process adds the remaining features needed to use this simulator from Jupyter Notebook (see sample notebook in the samples folder)

### TODO:
- [ ] Get package building and hosted from GH
- [ ] Add feed to project repo base so ppl who don't build locally can use in Juyputer

2020-07-25 17:41 UTC, crazy4pi314 commented
Ok I remember now why I can't have a config that adds the GH package registry feed, I'll remove and remove requirements for now.

2020-07-25 19:03 UTC, RolfHuisman commented on src/jupyter/ChpMagic.cs
> +                Summary = "Runs a given function or operation on the ToffoliSimulator target machine.",
think this is the CHP simulator

2020-07-25 19:09 UTC, RolfHuisman commented on src/StabilizerSimulator.cs
> +        internal new void MaybeDisplayDiagnostic(object displayable) =>
Maybe diagnostic ? Are we not sure we want diagnostics  :) ?

2020-07-25 19:11 UTC, RolfHuisman requested changes
We should clean up the descriptions.

2020-07-25 21:01 UTC, RolfHuisman approved these changes

2020-07-26 07:24 UTC, RolfHuisman approved these changes

2020-07-26 07:24 UTC, merged